services:
  unbound:
    restart: 'unless-stopped'
    container_name: 'unbound'
    image: 'mvance/unbound:latest'
    networks:
      default-frontend:
        ipv4_address: 172.20.0.1
    volumes:
      - '/etc/localtime:/etc/localtime:ro'

networks:
  default-frontend:
    external: true
