name: Repository Setup
description: Install Volta, restore Yarn cache, and install dependencies

runs:
  using: composite
  steps:
    - name: Install Volta
      uses: volta-cli/action@615a78f6c83e116339c53b94f3f82b4d6c0b7d18 # v5

    - name: Restore cached Yarn Dependencies
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
      with:
        path: |
          **/node_modules
          ~/.yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install Dependencies
      shell: bash
      run: yarn install --frozen-lockfile
