
services:
  adminer:
    extends:
      file: '../../libs/base/docker-compose.yml'
      service: 'base'
    container_name: 'adminer'
    image: 'adminer:latest'
    networks:
      - 'default-frontend'
    volumes:
      - './plugins/:/var/www/html/plugins-enabled/:ro'
    environment:
      ADMINER_DESIGN: 'pepa-linha'
      MYSQL_SERVERS: 'gitea-db,home-assistant-db,matomo-db'
      POSTGRES_SERVERS: 'mastodon-db,etesync-db'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.adminer.rule=Host(`adminer.${DEFAULT_DOMAIN_SUFFIX}`)'
      - 'traefik.http.routers.adminer.entrypoints=websecure'
      - 'traefik.http.routers.adminer.tls=true'
      - 'traefik.http.routers.adminer.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.adminer.tls.domains[0].main=adminer.${DEFAULT_DOMAIN_SUFFIX}'
      - 'traefik.http.routers.adminer.middlewares=intranet@file'
      - 'traefik.http.services.adminer.loadbalancer.server.port=8080'

networks:
  default-frontend:
    external: true
