log:
  # DEBUG, INFO, WARN, ERROR, FATAL, PANIC
  level: 'WARN'

providers:
  docker:
    exposedByDefault: false
    watch: true
    network: 'default-frontend'
    endpoint: 'tcp://traefik-dockerproxy:2375'
  file:
    directory: '/etc/traefik/dynamic'
    watch: true

api: {}

ping: {}

entryPoints:
  websecure:
    address: :443

certificatesResolvers:
  letsencrypt:
    acme:
      storage: '/certificates/acme.json'
      # use the staging server to test acme settings
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 10
        disablepropagationcheck: true
