log:
  level: 'INFO'

providers:
  docker:
    exposedByDefault: false
    watch: true
    network: 'default-frontend'
  file:
    directory: '/etc/traefik/dynamic'
    watch: true

api:
  insecure: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

certificatesResolvers:
  letsencrypt:
    acme:
      email: 'admin@example.com'
      storage: '/certificates/acme.json'
      # use the staging server to test acme settings
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      tlsChallenge: {}
