version: '3.8'

networks:
  default:
    external:
      name: docker-host-network

services:
  watchtower:
    extends:
      file: 'automation/watchtower/service.yml'
      service: 'watchtower'

  ofelia:
    extends:
      file: 'automation/ofelia/service.yml'
      service: 'ofelia'

  powershell-runner:
    extends:
      file: 'automation/ofelia/service.yml'
      service: 'powershell-runner'
