http:
  middlewares:
    intranet:
      chain:
        middlewares:
          - local-only
          - default
    intranet-authenticated:
      chain:
        middlewares:
          - authenticated
          - intranet
    extranet:
      chain:
        middlewares:
          - default
    extranet-authenticated:
      chain:
        middlewares:
          - authenticated
          - extranet
    default:
      chain:
        middlewares:
          - compressd
          - secured-redirect
          - secured-headers
    secured-headers:
      headers:
        forceSTSHeader: true
        stsPreload: true
        stsSeconds: '315360000'
        stsIncludeSubdomains: true
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
    secured-redirect:
      redirectScheme:
        scheme: https
        permanent: true
    compressd:
      compress: {}
    local-only:
      ipWhiteList:
        sourceRange:
          - '127.0.0.1/32'
          - '192.168.1.0/24'
    authenticated:
      forwardAuth:
        address: 'http://auth:4181'
        authResponseHeaders:
          - 'X-Forwarded-User'
