version: '3.8'

services:
  verdaccio:
    extends:
      file: '../../libs/base/docker-compose.yml'
      service: 'base'
    container_name: 'verdaccio'
    image: 'raeffs/verdaccio:latest'
    networks:
      - 'default-frontend'
    volumes:
      - 'verdaccio-data:/verdaccio/storage'
      - './config/config.yaml:/verdaccio/conf/config.yaml:ro'
      - './config/htpasswd:/verdaccio/htpasswd'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.verdaccio.rule=Host(`verdaccio.${DEFAULT_DOMAIN_SUFFIX}`)'
      - 'traefik.http.routers.verdaccio.entrypoints=websecure'
      - 'traefik.http.routers.verdaccio.tls=true'
      - 'traefik.http.routers.verdaccio.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.verdaccio.tls.domains[0].main=verdaccio.${DEFAULT_DOMAIN_SUFFIX}'
      - 'traefik.http.routers.verdaccio.middlewares=default@file'
      - 'traefik.http.services.verdaccio.loadbalancer.server.port=4873'

volumes:
  verdaccio-data:
    external: true

networks:
  default-frontend:
    external: true
