services:
  iperf:
    restart: 'unless-stopped'
    container_name: 'iperf'
    image: 'networkstatic/iperf3:latest'
    ports:
      - '5200:5201'
    networks:
      - 'default-frontend'
    command: '-s'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'

networks:
  default-frontend:
    external: true
  default-backend:
    external: true
