version: '3.8'

services:
  auth:
    container_name: 'auth'
    image: 'thomseddon/traefik-forward-auth:2'
    restart: 'unless-stopped'
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      DEFAULT_PROVIDER: oidc
      PROVIDERS_OIDC_ISSUER_URL: '${OIDC_ISSUER_URL}/'
      PROVIDERS_OIDC_CLIENT_ID: '${OIDC_CLIENT_ID}'
      PROVIDERS_OIDC_CLIENT_SECRET: '${OIDC_CLIENT_SECRET}'
      COOKIE_DOMAIN: 'https://${DOMAIN_SUFFIX}'
      AUTH_HOST: 'https://auth.${DOMAIN_SUFFIX}'
      SECRET: '${RANDOM_SECRET}'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.auth.rule=Host(`auth.${DOMAIN_SUFFIX}`)'
      - 'traefik.http.routers.auth.entrypoints=websecure'
      - 'traefik.http.routers.auth.tls=true'
      - 'traefik.http.routers.auth.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.auth.tls.domains[0].main=auth.${DOMAIN_SUFFIX}'
      - 'traefik.http.routers.auth.middlewares=intranet@file'
      - 'traefik.http.services.auth.loadbalancer.server.port=4181'
