services:
  baikal:
    container_name: 'baikal'
    image: 'ckulka/baikal:0.10.1-nginx'
    restart: 'unless-stopped'
    networks:
      - 'default-frontend'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - 'baikal-data:/var/www/baikal/Specific'
      - 'baikal-config:/var/www/baikal/config'
    environment:
      TZ: 'Europe/Zurich'
      BAIKAL_SKIP_CHOWN: 'TRUE'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.baikal.rule=Host(`${BAIKAL_DOMAIN}`)'
      - 'traefik.http.routers.baikal.entrypoints=websecure'
      - 'traefik.http.routers.baikal.tls=true'
      - 'traefik.http.routers.baikal.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.baikal.tls.domains[0].main=${BAIKAL_DOMAIN}'
      - 'traefik.http.routers.baikal.middlewares=intranet@file'
      - 'traefik.http.services.baikal.loadbalancer.server.port=80'

volumes:
  baikal-data:
    external: true
  baikal-config:
    external: true

networks:
  default-frontend:
    external: true
