services:
  navidrome:
    container_name: 'navidrome'
    image: 'ghcr.io/navidrome/navidrome:0.58.0'
    restart: 'unless-stopped'
    user: '65009:65009'
    mem_limit: 256M
    cap_drop:
      - 'ALL'
    security_opt:
      - 'no-new-privileges'
    networks:
      - 'default-frontend'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - 'navidrome-data:/data'
      - './config/navidrome.toml:/data/navidrome.toml:ro'
      - 'navidrome-music:/music:ro'
    environment:
      ND_LOGLEVEL: 'warn'
      ND_CONFIGFILE: '/data/navidrome.toml'
      ND_BASEURL: 'https://${NAVIDROME_DOMAIN}'
      ND_LASTFM_APIKEY: '${NAVIDROME_LASTFM_APIKEY}'
      ND_LASTFM_SECRET: '${NAVIDROME_LASTFM_SECRET}'
      ND_PASSWORDENCRYPTIONKEY: '${NAVIDROME_PASSWORD_ENCRYPTION_KEY}'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.navidrome.rule=Host(`${NAVIDROME_DOMAIN}`)'
      - 'traefik.http.routers.navidrome.entrypoints=websecure'
      - 'traefik.http.routers.navidrome.tls=true'
      - 'traefik.http.routers.navidrome.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.navidrome.tls.domains[0].main=${NAVIDROME_DOMAIN}'
      - 'traefik.http.routers.navidrome.middlewares=intranet@file'
      - 'traefik.http.services.navidrome.loadbalancer.server.port=4533'

volumes:
  navidrome-data:
    external: true
  navidrome-music:
    external: true

networks:
  default-frontend:
    external: true
