global:
  scrape_interval: 60s

scrape_configs:
  # pings endpoints
  - job_name: 'icmp-ping'
    scrape_interval: 60s
    metrics_path: /probe
    params:
      module: [icmp]
    file_sd_configs:
      - files:
          - 'icmp-ping.targets.json'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
  # executes a speedtest
  - job_name: speedtest
    scrape_interval: 60m
    scrape_timeout: 60s
    metrics_path: /metrics
    static_configs:
      - targets:
          - speedtest-exporter:9112
  # extracts information from pihole
  - job_name: 'pihole'
    metrics_path: /metrics
    static_configs:
      - targets:
          - pihole-exporter:9617
    metric_relabel_configs:
      # ignores all the go specific stuff
      - source_labels: [__name__]
        regex: 'go_(.+)'
        action: drop
