services:
  dozzle:
    container_name: 'dozzle'
    image: 'amir20/dozzle:latest'
    restart: 'unless-stopped'
    user: '65003:65003'
    read_only: true
    mem_limit: 64M
    cap_drop:
      - 'ALL'
    security_opt:
      - 'no-new-privileges'
    networks:
      - 'default-frontend'
      - 'dozzle-dockerproxynet'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      DOZZLE_NO_ANALYTICS: 'true'
      DOZZLE_REMOTE_HOST: 'tcp://dozzle-dockerproxy:2375'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.dozzle.rule=Host(`${DOZZLE_DOMAIN}`)'
      - 'traefik.http.routers.dozzle.entrypoints=websecure'
      - 'traefik.http.routers.dozzle.tls=true'
      - 'traefik.http.routers.dozzle.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.dozzle.tls.domains[0].main=${DOZZLE_DOMAIN}'
      - 'traefik.http.routers.dozzle.middlewares=intranet@file'
      - 'traefik.http.services.dozzle.loadbalancer.server.port=8080'
    depends_on:
      - 'dozzle-dockerproxy'

  dozzle-dockerproxy:
    extends:
      file: '../../libs/docker-socket-proxy/docker-compose.yml'
      service: 'docker-socket-proxy'
    container_name: 'dozzle-dockerproxy'
    command:
      - '-allowfrom=dozzle'
      - '-allowGET=/v1\..{2}/(containers/.*|events|info)|/_ping'
      - '-allowHEAD=/_ping'
    user: '65004:${DOZZLE_DOCKER_GID}'
    networks:
      - 'dozzle-dockerproxynet'

networks:
  default-frontend:
    external: true
  dozzle-dockerproxynet:
    name: 'dozzle-dockerproxynet'
    internal: true
    attachable: false
