services:
  mailpit:
    container_name: 'mailpit'
    image: 'axllent/mailpit:v1.31.0@sha256:c96991d9bef73594c246d89ca81411d4e916f03e76a7d2d72fa2ab5dd3c9ce24'
    restart: 'unless-stopped'
    user: '65023:65023'
    read_only: true
    mem_limit: 256M
    cap_drop:
      - 'ALL'
    security_opt:
      - 'no-new-privileges'
    networks:
      - 'default-frontend'
    tmpfs:
      - '/tmp'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - 'mailpit-data:/data'
    environment:
      MP_DATABASE: '/data/mailpit.db'
      MP_MAX_MESSAGES: '${MAILPIT_MAX_MESSAGES}'
      MP_MAX_AGE: '${MAILPIT_MAX_AGE}'
      MP_SMTP_AUTH_ACCEPT_ANY: 'true'
      MP_SMTP_AUTH_ALLOW_INSECURE: 'true'
      MP_UI_AUTH: '${MAILPIT_UI_USER}:${MAILPIT_UI_PASSWORD}'
      MP_DISABLE_VERSION_CHECK: 'true'
    healthcheck:
      test: ['CMD', '/mailpit', 'readyz']
      start_period: '10s'
      interval: '5s'
      timeout: '5s'
      retries: 3
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.mailpit.rule=Host(`${MAILPIT_DOMAIN}`)'
      - 'traefik.http.routers.mailpit.middlewares=default@file'
      - 'traefik.http.services.mailpit.loadbalancer.server.port=8025'

volumes:
  mailpit-data:
    external: true

networks:
  default-frontend:
    external: true
