log:
  filePath: '/var/log/traefik.log'
  level: 'WARN'

providers:
  docker:
    exposedByDefault: false
    watch: true
  file:
    directory: '/etc/traefik/dynamic'
    watch: true

api:
  insecure: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443

  public:
    address: :4430

  challenge:
    address: :800

certificatesResolvers:
  letsencrypt:
    acme:
      email: 'admin@example.com'
      storage: '/acme.json'
      caServer: 'https://acme-staging-v02.api.letsencrypt.org/directory'
      httpChallenge:
        entryPoint: 'challenge'
