log:
  level: 'INFO'

accessLog:
  filePath: '/var/log/access.log'
  filters:
    statusCodes:
      - '400-499'
  fields:
    headers:
      defaultMode: drop
      names:
        User-Agent: keep

providers:
  docker:
    exposedByDefault: false
    watch: true
  file:
    directory: '/etc/traefik/dynamic'
    watch: true

api:
  insecure: true

entryPoints:
  web:
    address: :80
  websecure:
    address: :443

certificatesResolvers:
  letsencrypt:
    acme:
      email: 'admin@example.com'
      storage: '/acme.json'
      httpChallenge:
        entryPoint: 'web'
