services:
  traefik:
    container_name: 'traefik'
    image: 'traefik:v3.5.1'
    restart: 'unless-stopped'
    entrypoint: []
    command: 'sh -c "/provision.sh && traefik"'
    user: '65001:65001'
    read_only: true
    mem_limit: 256M
    cap_drop:
      - 'ALL'
    security_opt:
      - 'no-new-privileges'
    ports:
      - '80:80'
      - '443:443'
    networks:
      - 'default-frontend'
      - 'traefik-dockerproxynet'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './provision.sh:/provision.sh:ro'
      - './config/dynamic:/etc/traefik/dynamic/:ro'
      - './config/traefik.yml:/traefik.yml:ro'
      - 'traefik-certificates:/certificates'
    environment:
      DEFAULT_DOMAIN_SUFFIX: '${DEFAULT_DOMAIN_SUFFIX}'
      CF_API_EMAIL: '${TRAEFIK_CF_EMAIL}'
      CF_DNS_API_TOKEN: '${TRAEFIK_CF_API_TOKEN}'
      CF_ZONE_API_TOKEN: '${TRAEFIK_CF_API_TOKEN}'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DOMAIN}`)'
      - 'traefik.http.routers.traefik.service=api@internal'
      - 'traefik.http.routers.traefik.tls=true'
      - 'traefik.http.routers.traefik.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.traefik.tls.domains[0].main=${TRAEFIK_DOMAIN}'
      - 'traefik.http.routers.traefik.middlewares=intranet@file'
    healthcheck:
      test: ['CMD', 'traefik', 'healthcheck', '--ping']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    depends_on:
      - 'traefik-dockerproxy'

  traefik-dockerproxy:
    extends:
      file: '../../libs/docker-socket-proxy/docker-compose.yml'
      service: 'docker-socket-proxy'
    container_name: 'traefik-dockerproxy'
    command:
      - '-allowfrom=traefik'
      - '-allowGET=/v1\..{1,2}/(version|containers/.*|events.*)'
    user: '65002:${TRAEFIK_DOCKER_GID}'
    networks:
      - 'traefik-dockerproxynet'

volumes:
  traefik-certificates:
    external: true

networks:
  default-frontend:
    external: true
  traefik-dockerproxynet:
    name: 'traefik-dockerproxynet'
    internal: true
    attachable: false
