version: '3.8'

services:
  lldap:
    extends:
      file: '../../libs/base/docker-compose.yml'
      service: 'base'
    container_name: 'lldap'
    image: 'nitnelave/lldap:stable'
    networks:
      - 'default-frontend'
    volumes:
      - 'lldap-data:/data'
    environment:
      LLDAP_JWT_SECRET: '${LLDAP_JWT_SECRET}'
      LLDAP_LDAP_USER_PASS: '${LLDAP_INITIAL_ADMIN_PASSWORD}'
      LLDAP_LDAP_BASE_DN: 'dc=example,dc=com'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.lldap.rule=Host(`${LLDAP_DOMAIN}`)'
      - 'traefik.http.routers.lldap.entrypoints=websecure'
      - 'traefik.http.routers.lldap.tls=true'
      - 'traefik.http.routers.lldap.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.lldap.tls.domains[0].main=${LLDAP_DOMAIN}'
      - 'traefik.http.routers.lldap.middlewares=intranet@file'
      - 'traefik.http.services.lldap.loadbalancer.server.port=17170'

volumes:
  lldap-data:
    external: true

networks:
  default-frontend:
    external: true
