version: '3.8'

services:
  iperf:
    extends:
      file: '../../libs/base/docker-compose.yml'
      service: 'base'
    container_name: 'iperf'
    image: 'networkstatic/iperf3:latest'
    ports:
      - '5200:5201'
    networks:
      - 'default-frontend'
    command: '-s'

networks:
  default-frontend:
    external: true
  default-backend:
    external: true
