version: '3.8'

services:
  etesync-web:
    extends:
      file: '../../libs/base/docker-compose.yml'
      service: 'base'
    container_name: 'etesync-web'
    image: 'victorrds/etesync:alpine'
    networks:
      - 'default-frontend'
      - 'default-backend'
    volumes:
      - 'etesync-data:/data'
    environment:
      SERVER: 'uvicorn'
      AUTO_UPDATE: 'true'
      DB_ENGINE: 'postgres'
      ALLOWED_HOSTS: 'etesync.${DEFAULT_DOMAIN_SUFFIX}'
      TIME_ZONE: 'Europe/Zurich'
      DATABASE_HOST: 'etesync-db'
      DATABASE_USER: 'etesync-user'
      DATABASE_NAME: 'etesync'
      DATABASE_PASSWORD: '${ETESYNC_POSTGRES_PASSWORD}'
      SUPER_USER: '${ETESYNC_ADMIN_USERNAME}'
      SUPER_PASS: '${ETESYNC_ADMIN_PASSWORD}'
    depends_on:
      etesync-db:
        condition: service_healthy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.etesync.rule=Host(`etesync.${DEFAULT_DOMAIN_SUFFIX}`)'
      - 'traefik.http.routers.etesync.entrypoints=websecure'
      - 'traefik.http.routers.etesync.tls=true'
      - 'traefik.http.routers.etesync.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.etesync.tls.domains[0].main=etesync.${DEFAULT_DOMAIN_SUFFIX}'
      - 'traefik.http.routers.etesync.middlewares=extranet@file'
      - 'traefik.http.services.etesync.loadbalancer.server.port=3735'

  etesync-db:
    extends:
      file: '../../libs/base/docker-compose.yml'
      service: 'base'
    container_name: 'etesync-db'
    image: 'postgres:alpine'
    networks:
      - 'default-backend'
    volumes:
      - 'etesync-db:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: 'etesync'
      POSTGRES_USER: 'etesync-user'
      POSTGRES_PASSWORD: '${ETESYNC_POSTGRES_PASSWORD}'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'etesync-user', '-d', 'etesync']
      interval: 5s
      timeout: 5s

volumes:
  etesync-data:
    external: true
  etesync-db:
    external: true

networks:
  default-frontend:
    external: true
  default-backend:
    external: true
