
services:
  leantime:
    extends:
      file: '../../libs/base/docker-compose.yml'
      service: 'base'
    container_name: 'leantime'
    image: 'leantime/leantime:latest'
    networks:
      - 'default-frontend'
      - 'default-backend'
    environment:
      LEAN_DB_HOST: 'leantime-db'
      LEAN_DB_DATABASE: 'leantime'
      LEAN_DB_USER: 'leantime-user'
      LEAN_DB_PASSWORD: '${LEANTIME_MYSQL_PASSWORD}'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.mastodon.rule=Host(`${LEANTIME_DOMAIN}`)'
      - 'traefik.http.routers.mastodon.entrypoints=websecure'
      - 'traefik.http.routers.mastodon.tls=true'
      - 'traefik.http.routers.mastodon.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.mastodon.tls.domains[0].main=${LEANTIME_DOMAIN}'
      - 'traefik.http.routers.mastodon.middlewares=extranet@file'
      - 'traefik.http.services.mastodon.loadbalancer.server.port=80'

  leantime-db:
    extends:
      file: '../../libs/base/docker-compose.yml'
      service: 'base'
    container_name: 'leantime-db'
    image: 'mariadb:latest'
    networks:
      - 'default-backend'
    volumes:
      - 'leantime-db:/var/lib/mysql'
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_DATABASE: 'leantime'
      MYSQL_USER: 'leantime-user'
      MYSQL_PASSWORD: '${LEANTIME_MYSQL_PASSWORD}'

volumes:
  leantime-db:
    external: true

networks:
  default-frontend:
    external: true
  default-backend:
    external: true
