services:
  whoami:
    image: 'ghcr.io/traefik/whoami:v1.11.0'
    container_name: 'whoami'
    restart: 'unless-stopped'
    user: '65010:65010'
    read_only: true
    mem_limit: 8M
    cap_drop:
      - 'ALL'
    security_opt:
      - 'no-new-privileges'
    networks:
      - 'default-frontend'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.whoami.rule=Host(`whoami.${DEFAULT_DOMAIN_SUFFIX}`)'
      - 'traefik.http.routers.whoami.entrypoints=websecure'
      - 'traefik.http.routers.whoami.tls=true'
      - 'traefik.http.routers.whoami.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.whoami.tls.domains[0].main=whoami.${DEFAULT_DOMAIN_SUFFIX}'
      - 'traefik.http.routers.whoami.middlewares=default@file'
      - 'traefik.http.services.whoami.loadbalancer.server.port=80'

networks:
  default-frontend:
    external: true
