services:
  pocket-id:
    container_name: 'pocket-id'
    image: 'ghcr.io/pocket-id/pocket-id:v2.6.0-distroless'
    restart: 'unless-stopped'
    user: '65008:65008'
    read_only: true
    mem_limit: 64M
    cap_drop:
      - 'ALL'
    security_opt:
      - 'no-new-privileges'
    networks:
      - 'default-frontend'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
    env_file: 'static.env'
    environment:
      APP_URL: 'https://${POCKET_ID_DOMAIN}'
      TRUST_PROXY: 'true'
      ENCRYPTION_KEY: '${POCKET_ID_ENCRYPTION_KEY}'
      DB_CONNECTION_STRING: 'postgres://${POCKET_ID_POSTGRES_USER}:${POCKET_ID_POSTGRES_PASSWORD}@${POCKET_ID_POSTGRES_SERVER}:${POCKET_ID_POSTGRES_PORT}/${POCKET_ID_POSTGRES_DATABASE}?sslmode=require'
      FILE_BACKEND: 'database'
      SMTP_HOST: '${POCKET_ID_SMTP_HOST}'
      SMTP_PORT: '${POCKET_ID_SMTP_PORT}'
      SMTP_FROM: '${POCKET_ID_SMTP_USER}'
      SMTP_USER: '${POCKET_ID_SMTP_USER}'
      SMTP_PASSWORD: '${POCKET_ID_SMTP_PASSWORD}'
      SMTP_TLS: '${POCKET_ID_SMTP_TLS}'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.pocket-id.rule=Host(`${POCKET_ID_DOMAIN}`)'
      - 'traefik.http.routers.pocket-id.entrypoints=websecure'
      - 'traefik.http.routers.pocket-id.tls=true'
      - 'traefik.http.routers.pocket-id.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.pocket-id.tls.domains[0].main=${POCKET_ID_DOMAIN}'
      - 'traefik.http.routers.pocket-id.middlewares=default@file'
      - 'traefik.http.services.pocket-id.loadbalancer.server.port=1411'
    healthcheck:
      test: ['CMD', '/app/pocket-id', 'healthcheck']
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s

networks:
  default-frontend:
    external: true
