
services:
  portainer:
    extends:
      file: '../../libs/base/docker-compose.yml'
      service: 'base'
    container_name: 'portainer'
    image: 'portainer/portainer-ce'
    networks:
      - 'default-frontend'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - 'portainer-data:/data'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.portainer.rule=Host(`${PORTAINER_DOMAIN}`)'
      - 'traefik.http.routers.portainer.entrypoints=websecure'
      - 'traefik.http.routers.portainer.tls=true'
      - 'traefik.http.routers.portainer.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.portainer.tls.domains[0].main=${PORTAINER_DOMAIN}'
      - 'traefik.http.routers.portainer.middlewares=intranet@file'
      - 'traefik.http.services.portainer.loadbalancer.server.port=9000'

volumes:
  portainer-data:
    external: true

networks:
  default-frontend:
    external: true
