version: '3.8'

services:
  matomo:
    extends:
      file: '../../libs/base/docker-compose.yml'
      service: 'base'
    container_name: 'matomo'
    image: 'bitnami/matomo:latest'
    volumes:
      - 'matomo-data:/bitnami/matomo/'
    environment:
      MATOMO_USERNAME: '${MATOMO_INITIAL_USER}'
      MATOMO_PASSWORD: '${MATOMO_INITIAL_PASSWORD}'
      MATOMO_DATABASE_HOST: 'matomo-db'
      MATOMO_DATABASE_USER: 'matomo-user'
      MATOMO_DATABASE_PASSWORD: '${MATOMO_MYSQL_PASSWORD}'
      MATOMO_DATABASE_NAME: 'matomo-db'
    depends_on:
      - 'matomo-db'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.matomo.rule=Host(`matomo.${DEFAULT_DOMAIN_SUFFIX}`)'
      - 'traefik.http.routers.matomo.entrypoints=websecure'
      - 'traefik.http.routers.matomo.tls=true'
      - 'traefik.http.routers.matomo.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.matomo.tls.domains[0].main=matomo.${DEFAULT_DOMAIN_SUFFIX}'
      - 'traefik.http.routers.matomo.middlewares=default@file'
      - 'traefik.http.services.matomo.loadbalancer.server.port=8080'

  matomo-db:
    extends:
      file: '../../libs/base/docker-compose.yml'
      service: 'base'
    container_name: 'matomo-db'
    image: 'mariadb:latest'
    volumes:
      - 'matomo-db:/var/lib/mysql'
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_DATABASE: 'matomo-db'
      MYSQL_USER: 'matomo-user'
      MYSQL_PASSWORD: '${MATOMO_MYSQL_PASSWORD}'

volumes:
  matomo-data:
    external: true
  matomo-db:
    external: true

networks:
  default:
    external:
      name: docker-host-network
