# add external services and routers here
# the websecure entrypoint provides the entrypoint, tls and certresolver defaults
# http:
#   routers:
#     external:
#       rule: Host(`example.ch`)
#       service: external@file
#       middlewares:
#         - default@file
#   services:
#     external:
#       loadBalancer:
#         servers:
#           - url: http://external-service
