http:
  middlewares:
    default:
      chain:
        middlewares:
          - compressd
          - secured-redirect
          - secured-headers
    secured-headers:
      headers:
        forceSTSHeader: true
        stsPreload: true
        stsSeconds: '315360000'
        stsIncludeSubdomains: true
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
    secured-redirect:
      redirectScheme:
        scheme: https
        permanent: true
    compressd:
      compress: {}
