
services:
  wireguard:
    extends:
      file: '../../libs/base/docker-compose.yml'
      service: 'base'
    container_name: 'wireguard'
    image: 'linuxserver/wireguard:latest'
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - ${WIREGUARD_PORT}:51820/udp
    networks:
      - 'default-frontend'
    volumes:
      - '/lib/modules:/lib/modules'
      - 'wireguard-data:/config'
    environment:
      PUID: 1000
      PGID: 1000
      SERVERURL: 'wireguard.${DEFAULT_DOMAIN_SUFFIX}'
      SERVERPORT: '${WIREGUARD_PORT}'
      PEERS: '${WIREGUARD_PEERS}'
      PEERDNS: '${WIREGUARD_PEERDNS}'

volumes:
  wireguard-data:
    external: true

networks:
  default-frontend:
    external: true
