services:
  miniflux:
    extends:
      file: '../miniflux/docker-compose.yml'
      service: 'miniflux'
    networks:
      - 'default-frontend'
      - 'default-backend'
    depends_on:
      miniflux-db:
        condition: 'service_healthy'

  miniflux-db:
    extends:
      file: '../../../libs/postgres/docker-compose.yml'
      service: 'postgres'
    container_name: 'miniflux-db'
    networks:
      - 'default-backend'
    volumes:
      - 'miniflux-db:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: '${MINIFLUX_POSTGRES_PASSWORD}'

volumes:
  miniflux-db:
    external: true

networks:
  default-frontend:
    external: true
  default-backend:
    external: true
