services:
  redmine:
    container_name: 'redmine'
    image: 'redmine:6.1.3'
    restart: 'unless-stopped'
    user: '999:999'
    mem_limit: 1G
    cap_drop:
      - 'ALL'
    security_opt:
      - 'no-new-privileges'
    networks:
      - 'default-frontend'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - 'redmine-files:/usr/src/redmine/files'
      - './configuration.yml:/usr/src/redmine/config/configuration.yml:ro'
      # git submodule pinned to https://github.com/enricohuang/redmine_oidc
      - './plugins/redmine_oidc:/usr/src/redmine/plugins/redmine_oidc:ro'
      # git submodule pinned to https://github.com/gagnieray/opale
      - './themes/opale:/usr/src/redmine/themes/opale:ro'
    environment:
      REDMINE_DB_POSTGRES: '${REDMINE_POSTGRES_SERVER}'
      REDMINE_DB_PORT: '${REDMINE_POSTGRES_PORT}'
      REDMINE_DB_USERNAME: '${REDMINE_POSTGRES_USER}'
      REDMINE_DB_PASSWORD: '${REDMINE_POSTGRES_PASSWORD}'
      REDMINE_DB_DATABASE: '${REDMINE_POSTGRES_DATABASE}'
      REDMINE_SECRET_KEY_BASE: '${REDMINE_SECRET_KEY_BASE}'
      REDMINE_PLUGINS_MIGRATE: '1'
      PGSSLMODE: 'verify-full'
      PGSSLROOTCERT: '/etc/ssl/certs/ca-certificates.crt'
      REDMINE_SMTP_HOST: '${REDMINE_SMTP_HOST}'
      REDMINE_SMTP_PORT: '${REDMINE_SMTP_PORT}'
      REDMINE_SMTP_USER: '${REDMINE_SMTP_USER}'
      REDMINE_SMTP_PASSWORD: '${REDMINE_SMTP_PASSWORD}'
    healthcheck:
      test:
        [
          'CMD',
          'ruby',
          '-rnet/http',
          '-e',
          'exit(Net::HTTP.get_response(URI("http://localhost:3000/")).code.to_i < 400 ? 0 : 1)',
        ]
      start_period: '90s'
      interval: '30s'
      timeout: '10s'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.redmine.rule=Host(`${REDMINE_DOMAIN}`)'
      - 'traefik.http.routers.redmine.entrypoints=websecure'
      - 'traefik.http.routers.redmine.tls=true'
      - 'traefik.http.routers.redmine.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.redmine.tls.domains[0].main=${REDMINE_DOMAIN}'
      - 'traefik.http.routers.redmine.middlewares=default@file'
      - 'traefik.http.services.redmine.loadbalancer.server.port=3000'

volumes:
  redmine-files:
    external: true

networks:
  default-frontend:
    external: true
