
services:
  openproject-base:
    extends:
      file: '../../libs/base/docker-compose.yml'
      service: 'base'
    image: 'openproject/community:12'
    volumes:
      - 'openproject-data:/var/openproject/assets'
    environment:
      OPENPROJECT_SECRET_KEY_BASE: '${OPENPROJECT_SECRET_KEY_BASE}'
      OPENPROJECT_HOST__NAME: '${OPENPROJECT_DOMAIN}'
      OPENPROJECT_HTTPS: 'true'
      DATABASE_URL: 'postgres://openproject-user:${OPENPROJECT_POSTGRES_PASSWORD}@openproject-db:5432/openproject'
      OPENPROJECT_CACHE__MEMCACHE__SERVER: 'openproject-cache:11211'
      OPENPROJECT_EE__MANAGER__VISIBLE: 'false'
