
services:
  prometheus:
    extends:
      file: '../../libs/base/docker-compose.yml'
      service: 'base'
    container_name: 'prometheus'
    image: 'prom/prometheus:latest'
    user: 'root'
    networks:
      - 'default-frontend'
    volumes:
      - './config/:/etc/prometheus/:ro'
      - 'prometheus-data:/prometheus/'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.prometheus.rule=Host(`prometheus.${DEFAULT_DOMAIN_SUFFIX}`)'
      - 'traefik.http.routers.prometheus.entrypoints=websecure'
      - 'traefik.http.routers.prometheus.tls=true'
      - 'traefik.http.routers.prometheus.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.prometheus.tls.domains[0].main=prometheus.${DEFAULT_DOMAIN_SUFFIX}'
      - 'traefik.http.routers.prometheus.middlewares=intranet@file'
      - 'traefik.http.services.prometheus.loadbalancer.server.port=9090'

  blackbox-exporter:
    extends:
      file: '../../libs/base/docker-compose.yml'
      service: 'base'
    container_name: 'blackbox-exporter'
    image: 'prom/blackbox-exporter:latest'
    networks:
      - 'default-frontend'
    volumes:
      - './config-blackbox-exporter:/etc/blackbox_exporter:ro'

  speedtest-exporter:
    extends:
      file: '../../libs/base/docker-compose.yml'
      service: 'base'
    container_name: 'speedtest-exporter'
    image: 'raeffs/speedtest-exporter:latest'
    networks:
      - 'default-frontend'

  pihole-exporter:
    extends:
      file: '../../libs/base/docker-compose.yml'
      service: 'base'
    container_name: 'pihole-exporter'
    image: 'ekofr/pihole-exporter:latest'
    networks:
      - 'default-frontend'
    environment:
      PIHOLE_HOSTNAME: 'pihole'
      PIHOLE_PASSWORD: '${PIHOLE_PASSWORD}'
      INTERVAL: '30s'
      PORT: '9617'

volumes:
  prometheus-data:
    external: true

networks:
  default-frontend:
    external: true
