
services:
  commento:
    extends:
      file: '../../libs/base/docker-compose.yml'
      service: 'base'
    container_name: 'commento'
    image: 'caroga/commentoplusplus:latest'
    networks:
      - 'default-frontend'
      - 'default-backend'
    environment:
      COMMENTO_ORIGIN: 'https://commento.${DEFAULT_DOMAIN_SUFFIX}'
      COMMENTO_PORT: '8080'
      COMMENTO_POSTGRES: 'postgres://commento-user:${COMMENTO_POSTGRES_PASSWORD}@commento-db:5432/commento?sslmode=disable'
    depends_on:
      - 'commento-db'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.commento.rule=Host(`commento.${DEFAULT_DOMAIN_SUFFIX}`)'
      - 'traefik.http.routers.commento.entrypoints=websecure'
      - 'traefik.http.routers.commento.tls=true'
      - 'traefik.http.routers.commento.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.commento.tls.domains[0].main=commento.${DEFAULT_DOMAIN_SUFFIX}'
      - 'traefik.http.routers.commento.middlewares=intranet@file'
      - 'traefik.http.services.commento.loadbalancer.server.port=8080'

  commento-db:
    extends:
      file: '../../libs/base/docker-compose.yml'
      service: 'base'
    container_name: 'commento-db'
    image: 'postgres'
    networks:
      - 'default-backend'
    volumes:
      - 'commento-db:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: 'commento'
      POSTGRES_USER: 'commento-user'
      POSTGRES_PASSWORD: '${COMMENTO_POSTGRES_PASSWORD}'

volumes:
  commento-db:
    external: true

networks:
  default-frontend:
    external: true
  default-backend:
    external: true
