version: '3.8'

services:
  wireguard:
    container_name: 'wireguard'
    image: 'linuxserver/wireguard:latest'
    restart: 'unless-stopped'
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - ${WIREGUARD_PORT}:${WIREGUARD_PORT}/udp
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
      - '/lib/modules:/lib/modules'
      - 'wireguard:/config'
    environment:
      PUID: 1000
      PGID: 1000
      SERVERURL: 'wireguard.${DOMAIN_SUFFIX}'
      SERVERPORT: '${WIREGUARD_PORT}'
      PEERS: '${WIREGUARD_PEERS}'
