version: '3.8'

services:
  cookbook:
    container_name: 'cookbook'
    image: 'raeffs/cookbook-web'
    restart: 'unless-stopped'
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
      - './config/default.conf:/etc/nginx/conf.d/default.conf:ro'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.cookbook.rule=Host(`cookbook.${DOMAIN_SUFFIX}`)'
      - 'traefik.http.routers.cookbook.entrypoints=websecure'
      - 'traefik.http.routers.cookbook.tls=true'
      - 'traefik.http.routers.cookbook.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.cookbook.tls.domains[0].main=cookbook.${DOMAIN_SUFFIX}'
      - 'traefik.http.routers.cookbook.middlewares=default@file'
      - 'traefik.http.services.cookbook.loadbalancer.server.port=80'

  cookbook-api:
    container_name: 'cookbook-api'
    image: 'raeffs/cookbook-api'
    restart: 'unless-stopped'
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      ConnectionStrings__DataContext: 'Host=cookbook-db;Database=cookbook;Username=cookbook-user;Password=${COOKBOOK_POSTGRES_PASSWORD}'
      ASPNETCORE_URLS: 'http://+:5000'
      ASPNETCORE_ENVIRONMENT: 'production'

  cookbook-db:
    container_name: 'cookbook-db'
    image: 'postgres'
    restart: 'unless-stopped'
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
      - 'cookbook-db:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: 'cookbook'
      POSTGRES_USER: 'cookbook-user'
      POSTGRES_PASSWORD: '${COOKBOOK_POSTGRES_PASSWORD}'
