name: Watchtower Checks

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:
  watchtower-healthcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: ./.github/actions/setup

      - name: Healthcheck
        uses: ./.github/actions/healthcheck
        with:
          app-name: watchtower
          compose-file: apps/watchtower/docker-compose.yml
