name: Whoami Checks

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:
  whoami-healthcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: ./.github/actions/setup

      - name: Healthcheck
        uses: ./.github/actions/healthcheck
        with:
          app-name: whoami
          compose-file: apps/whoami/docker-compose.yml
