name: Baikal Checks

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:
  baikal-healthcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: ./.github/actions/setup

      - name: Healthcheck
        uses: ./.github/actions/healthcheck
        with:
          app-name: baikal
          compose-file: apps/baikal/docker-compose.yml
