name: PR Build

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: ./.github/actions/setup

      - name: Run build target on docker-compose project
        run: yarn nx run docker-compose:build
