name: PR Build

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run build target on docker-compose project
        run: yarn nx run docker-compose:build
