name: PR Build

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run build target on docker-compose project
        run: yarn nx run docker-compose:build
