services:
  seq:
    container_name: 'seq'
    image: 'datalust/seq:2026.1@sha256:91e93ff21b1e61f0bbd0854a633a94b925d771b227e98269c740079f5092f740'
    restart: 'unless-stopped'
    user: '999:999'
    read_only: true
    mem_limit: 1G
    cap_drop:
      - 'ALL'
    cap_add:
      - 'NET_BIND_SERVICE'
    security_opt:
      - 'no-new-privileges'
    networks:
      - 'default-frontend'
    tmpfs:
      - '/tmp'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - 'seq-data:/data'
    environment:
      ACCEPT_EULA: 'Y'
      SEQ_FIRSTRUN_ADMINUSERNAME: '${SEQ_INITIAL_USER}'
      SEQ_FIRSTRUN_ADMINPASSWORD: '${SEQ_INITIAL_PASSWORD}'
      SEQ_FIRSTRUN_REQUIREAUTHENTICATIONFORHTTPINGESTION: 'True'
      SEQ_API_CANONICALURI: 'https://${SEQ_DOMAIN}'
    healthcheck:
      test: 'curl -f http://localhost/health'
      start_period: '10s'
      interval: '5s'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.seq.rule=Host(`${SEQ_DOMAIN}`)'
      - 'traefik.http.routers.seq.middlewares=default@file'
      - 'traefik.http.routers.seq.service=seq'
      - 'traefik.http.services.seq.loadbalancer.server.port=80'
      - 'traefik.http.routers.seq-ingest.rule=Host(`${SEQ_INGEST_DOMAIN}`)'
      - 'traefik.http.routers.seq-ingest.middlewares=default@file'
      - 'traefik.http.routers.seq-ingest.service=seq-ingest'
      - 'traefik.http.services.seq-ingest.loadbalancer.server.port=5341'

volumes:
  seq-data:
    external: true

networks:
  default-frontend:
    external: true
