version: '3.8'

services:
  gitea:
    extends:
      file: '../../libs/base/docker-compose.yml'
      service: 'base'
    container_name: 'gitea'
    image: 'gitea/gitea:1'
    ports:
      - '2222:2222'
    volumes:
      - 'gitea-data:/data/'
      - './custom/public/:/data/gitea/public/:ro'
      - './custom/templates/:/data/gitea/templates/:ro'
      # https://github.com/go-gitea/gitea/blob/master/docker/root/etc/templates/app.ini
      - './template.app.ini:/etc/templates/app.ini:ro'
    environment:
      APP_NAME: 'Gitea'
      RUN_MODE: 'prod'
      DOMAIN: 'gitea.${DEFAULT_DOMAIN_SUFFIX}'
      ROOT_URL: 'https://gitea.${DEFAULT_DOMAIN_SUFFIX}'
      SSH_DOMAIN: 'gitea.${DEFAULT_DOMAIN_SUFFIX}'
      SSH_PORT: '2222'
      SSH_LISTEN_PORT: '2222'
      DB_TYPE: 'mysql'
      DB_HOST: 'gitea-db:3306'
      DB_NAME: 'gitea-db'
      DB_USER: 'gitea-user'
      DB_PASSWD: '${GITEA_MYSQL_PASSWORD}'
      INSTALL_LOCK: 'true'
      GITEA_CUSTOM: '/data/gitea'
    depends_on:
      - 'gitea-db'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.gitea.rule=Host(`gitea.${DEFAULT_DOMAIN_SUFFIX}`)'
      - 'traefik.http.routers.gitea.entrypoints=websecure'
      - 'traefik.http.routers.gitea.tls=true'
      - 'traefik.http.routers.gitea.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.gitea.tls.domains[0].main=gitea.${DEFAULT_DOMAIN_SUFFIX}'
      - 'traefik.http.routers.gitea.middlewares=default@file'
      - 'traefik.http.services.gitea.loadbalancer.server.port=3000'

  gitea-db:
    extends:
      file: '../../libs/base/docker-compose.yml'
      service: 'base'
    container_name: 'gitea-db'
    image: 'mariadb:latest'
    volumes:
      - 'gitea-db:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: 'gitea-db'
      MYSQL_USER: 'gitea-user'
      MYSQL_PASSWORD: '${GITEA_MYSQL_PASSWORD}'

volumes:
  gitea-data:
    external: true
  gitea-db:
    external: true

networks:
  default:
    external:
      name: docker-host-network
