
services:
  gitea:
    extends:
      file: '../../libs/base/docker-compose.yml'
      service: 'base'
    container_name: 'gitea'
    image: 'gitea/gitea:1'
    ports:
      - '2222:2222'
    networks:
      - 'default-frontend'
      - 'default-backend'
    volumes:
      - 'gitea-data:/data/'
      - '/etc/timezone:/etc/timezone:ro'
      - './custom/public/:/data/gitea/public/:ro'
      - './custom/templates/:/data/gitea/templates/:ro'
      # https://github.com/go-gitea/gitea/blob/master/docker/root/etc/templates/app.ini
      - './template.app.ini:/etc/templates/app.ini:ro'
    environment:
      APP_NAME: 'Gitea'
      RUN_MODE: 'prod'
      DOMAIN: '${GITEA_DOMAIN}'
      ROOT_URL: 'https://${GITEA_DOMAIN}'
      SSH_DOMAIN: '${GITEA_DOMAIN}'
      SSH_PORT: '2222'
      SSH_LISTEN_PORT: '2222'
      DB_TYPE: 'postgres'
      DB_HOST: 'gitea-db:5432'
      DB_NAME: 'gitea'
      DB_USER: 'gitea-user'
      DB_PASSWD: '${GITEA_POSTGRES_PASSWORD}'
      INSTALL_LOCK: 'true'
      GITEA_CUSTOM: '/data/gitea'
    depends_on:
      gitea-db:
        condition: 'service_healthy'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.gitea.rule=Host(`${GITEA_DOMAIN}`)'
      - 'traefik.http.routers.gitea.entrypoints=websecure'
      - 'traefik.http.routers.gitea.tls=true'
      - 'traefik.http.routers.gitea.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.gitea.tls.domains[0].main=${GITEA_DOMAIN}'
      - 'traefik.http.routers.gitea.middlewares=default@file'
      - 'traefik.http.services.gitea.loadbalancer.server.port=3000'

  gitea-db:
    extends:
      file: '../../libs/base/docker-compose.yml'
      service: 'base'
    container_name: 'gitea-db'
    image: 'postgres'
    networks:
      - 'default-backend'
    volumes:
      - 'gitea-db:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: 'gitea'
      POSTGRES_USER: 'gitea-user'
      POSTGRES_PASSWORD: '${GITEA_POSTGRES_PASSWORD}'
    healthcheck:
      test: 'pg_isready -U gitea-user -d gitea'
      start_period: '5s'
      interval: '5s'

volumes:
  gitea-data:
    external: true
  gitea-db:
    external: true

networks:
  default-frontend:
    external: true
  default-backend:
    external: true
